# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Property tests for the credential-resolution seam routing.

Property: All tool sessions flow through the active resolver
Validates: Requirements Tools resolve credentials through the seam
"""

import contextlib
import pytest
from awslabs.aws_healthomics_mcp_server.utils.aws_utils import (
    CredentialRequest,
    create_aws_client,
    get_account_id,
    get_active_resolver,
    get_aws_session,
    get_codebuild_client,
    get_codeconnections_client,
    get_ecr_client,
    get_iam_client,
    get_logs_client,
    get_omics_client,
    get_partition,
    set_active_resolver,
)
from hypothesis import given, settings
from hypothesis import strategies as st
from unittest.mock import MagicMock


class _RecordingResolver:
    """Fake credential resolver that records every request it receives.

    Returns a ``MagicMock`` standing in for a ``boto3.Session`` whose ``client()``
    yields a ``MagicMock`` so downstream calls (e.g. ``get_account_id`` /
    ``get_partition`` calling STS ``get_caller_identity``) do not crash.
    """

    def __init__(self) -> None:
        self.requests: list[CredentialRequest] = []

    def resolve(self, request: CredentialRequest) -> MagicMock:
        self.requests.append(request)
        session = MagicMock(name='RecordedSession')
        session.client.return_value = MagicMock(name='RecordedClient')
        return session


def _optional_region():
    """Region input: present (arbitrary string) or absent (None)."""
    return st.one_of(st.none(), st.text(min_size=1, max_size=24))


def _optional_profile():
    """Profile input: present (arbitrary string) or absent (None)."""
    return st.one_of(st.none(), st.text(min_size=1, max_size=24))


def _service_names():
    """Service names accepted by the generic client factory."""
    return st.sampled_from(['omics', 'logs', 's3', 'sts', 'ecr', 'iam', 'codebuild'])


# Helpers sharing the (region_name, profile_name) keyword signature that must
# obtain their session through the active resolver seam.
_SAME_SIGNATURE_HELPERS = [
    get_aws_session,
    get_omics_client,
    get_logs_client,
    get_codeconnections_client,
    get_ecr_client,
    get_codebuild_client,
    get_iam_client,
    get_account_id,
    get_partition,
]


@contextlib.contextmanager
def _active_recording_resolver():
    """Install a recording fake resolver and restore the original on exit.

    Implemented as a context manager (rather than a function-scoped fixture) so it
    resets cleanly for every input generated by ``@given``.
    """
    original = get_active_resolver()
    resolver = _RecordingResolver()
    set_active_resolver(resolver)
    # get_partition is lru_cache'd; clear so the call under test actually invokes
    # the resolver rather than returning a memoized value.
    get_partition.cache_clear()
    try:
        yield resolver
    finally:
        set_active_resolver(original)
        get_partition.cache_clear()


class TestAllToolSessionsFlowThroughResolver:
    """Property: All tool sessions flow through the active resolver.

    Validates: Requirements Tools resolve credentials through the seam.
    """

    @pytest.mark.parametrize('helper', _SAME_SIGNATURE_HELPERS, ids=lambda helper: helper.__name__)
    @settings(max_examples=100)
    @given(region=_optional_region(), profile=_optional_profile())
    def test_helper_flows_through_active_resolver(self, helper, region, profile):
        """Each (region_name, profile_name) helper resolves via the active resolver.

        The helper must invoke the active resolver exactly once with a matching
        ``CredentialRequest`` carrying the supplied region/profile (absent as None).
        """
        with _active_recording_resolver() as recording_resolver:
            helper(region_name=region, profile_name=profile)

            assert len(recording_resolver.requests) == 1
            request = recording_resolver.requests[0]
            assert isinstance(request, CredentialRequest)
            assert request.region == region
            assert request.profile == profile

    @settings(max_examples=100)
    @given(
        region=_optional_region(),
        profile=_optional_profile(),
        service_name=_service_names(),
    )
    def test_create_aws_client_flows_through_active_resolver(self, region, profile, service_name):
        """The generic client factory resolves its session via the active resolver."""
        with _active_recording_resolver() as recording_resolver:
            create_aws_client(service_name, region_name=region, profile_name=profile)

            assert len(recording_resolver.requests) == 1
            request = recording_resolver.requests[0]
            assert isinstance(request, CredentialRequest)
            assert request.region == region
            assert request.profile == profile
