# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Tenant isolation property test for concurrent customer-role identities.

Property-based tests asserting that, while multiple inbound ``jwt`` identities are
resolved concurrently, each request observes only its own ``CredentialContext`` and
its own per-identity partition cache entry, never another concurrent request's.

This module extends the ``contextvars`` isolation + concurrency pattern established
in ``tests/test_partition_cache_isolation.py`` (per-identity partition cache keying)
and ``tests/test_request_scoped_resolver.py`` (interleaved ``asyncio`` workers each
carrying a distinct context). STS is always stubbed via a patched
``CredentialContext.build_session``; no real AWS calls are made.
"""

import asyncio
import contextlib
from awslabs.aws_healthomics_mcp_server.utils.aws_utils import (
    CredentialContext,
    RequestScopedCredentialResolver,
    get_active_resolver,
    get_credential_context,
    get_partition,
    reset_credential_context,
    set_active_resolver,
    set_credential_context,
)
from hypothesis import HealthCheck, given, settings
from hypothesis import strategies as st
from unittest.mock import MagicMock, patch


# Distinct identity strings for concurrent contexts. Printable, non-space ASCII
# keeps the derived access key ids readable; ``unique=True`` guarantees each
# concurrent worker carries a distinct identity (and therefore a distinct
# identity_key), which is what makes cross-tenant leakage observable.
identity_lists = st.lists(
    st.text(
        alphabet=st.characters(min_codepoint=0x21, max_codepoint=0x7E),
        min_size=1,
        max_size=10,
    ),
    unique=True,
    min_size=2,
    max_size=5,
)

# Region values used both in the partition cache key and passed to
# ``build_session``. A small set of realistic regions across partitions exercises
# the (identity_key, region) keying without affecting the partition the stubbed
# STS call reports.
region_strategy = st.sampled_from(
    [
        'us-east-1',
        'us-west-2',
        'eu-west-1',
        'cn-north-1',
        'us-gov-west-1',
    ]
)


def _jwt_context_for(identity: str) -> CredentialContext:
    """Build a ``source='jwt'`` CredentialContext with a distinct identity_key.

    Every secret-bearing field embeds the identity so that any cross-tenant leak
    (a worker observing a neighbor's context) surfaces as a mismatched field.
    """
    return CredentialContext(
        identity_key=identity,
        access_key_id=f'AKIA-{identity}',
        secret_access_key=f'secret-{identity}',
        session_token=f'token-{identity}',
        source='jwt',
    )


def _make_build_session(partition_by_identity, sts_calls):
    """Return a ``CredentialContext.build_session`` replacement keyed by identity.

    The session built for a given context returns an STS client whose
    ``get_caller_identity`` yields an ARN carrying that identity's partition. The
    ``identity_key`` selects which partition/ARN to return, so a request that ever
    observed another identity's partition would surface as a mismatch.
    """

    def build_session(self, region):
        identity = self.identity_key
        partition = partition_by_identity[identity]
        arn = f'arn:{partition}:sts::000000000000:assumed-role/role/{identity}'

        def _record():
            sts_calls[identity] = sts_calls.get(identity, 0) + 1
            return {'Arn': arn}

        sts_client = MagicMock()
        sts_client.get_caller_identity.side_effect = _record
        session = MagicMock()
        session.client.return_value = sts_client
        return session

    return build_session


@contextlib.contextmanager
def _active_request_scoped_resolver():
    """Install a ``RequestScopedCredentialResolver`` and restore the original on exit.

    Implemented as a context manager (rather than a function-scoped fixture) so it
    resets cleanly for every input generated by ``@given``. The partition cache is
    cleared on entry and exit so cross-example state never leaks.
    """
    original = get_active_resolver()
    set_active_resolver(RequestScopedCredentialResolver())
    get_partition.cache_clear()  # type: ignore[attr-defined]
    try:
        yield
    finally:
        get_partition.cache_clear()  # type: ignore[attr-defined]
        set_active_resolver(original)


class TestTenantIsolation:
    """Property: Tenant isolation.

    Validates: Requirements Tenant Isolation And Cross-Tenant Boundary.
    """

    @given(identities=identity_lists, region=region_strategy)
    @settings(max_examples=50, suppress_health_check=[HealthCheck.function_scoped_fixture])
    def test_concurrent_identities_never_observe_another_tenant(self, identities, region):
        """Property: Tenant isolation.

        For a set of distinct authenticated identities resolved concurrently, each
        request installs its own ``jwt`` ``CredentialContext`` and interleaves with
        the others via ``asyncio.gather``. Each worker asserts, at every await
        boundary, that it observes only its OWN ``CredentialContext`` (identity_key,
        access key id, and source), and it resolves its OWN partition cache entry —
        keyed by its own identity_key — never a value derived for a different
        identity. Each identity is mapped to a distinct partition, so any
        cross-tenant leakage would surface as a request observing a context or a
        partition belonging to another identity.

        Validates: Requirements Tenant Isolation And Cross-Tenant Boundary.
        """
        partition_by_identity = {
            identity: f'awspart{index}' for index, identity in enumerate(identities)
        }
        sts_calls: dict[str, int] = {}

        async def _worker(identity: str):
            context = _jwt_context_for(identity)
            # contextvars are copied per asyncio task, so setting/resetting inside
            # the worker coroutine confines this context to this task alone.
            token = set_credential_context(context)
            try:
                # Force interleaving so that, if any state leaked between tasks, a
                # concurrent worker could overwrite it between these awaits.
                await asyncio.sleep(0)
                observed = get_credential_context()
                await asyncio.sleep(0)
                partition = get_partition(region_name=region)
                await asyncio.sleep(0)
                return identity, observed, partition
            finally:
                reset_credential_context(token)

        async def _run_all():
            return await asyncio.gather(*(_worker(identity) for identity in identities))

        with (
            _active_request_scoped_resolver(),
            patch.object(
                CredentialContext,
                'build_session',
                _make_build_session(partition_by_identity, sts_calls),
            ),
        ):
            results = asyncio.run(_run_all())
            # Snapshot the per-identity partition cache after all workers complete so
            # the (identity_key, region) keying can be asserted directly.
            from awslabs.aws_healthomics_mcp_server.utils import aws_utils

            cache_snapshot = dict(aws_utils._partition_cache)

        for identity, observed, partition in results:
            # Requirement 6.2: the request ran under the Credential_Context derived
            # for its OWN authenticated identity, never another concurrent request's.
            assert observed is not None
            assert observed.identity_key == identity
            assert observed.access_key_id == f'AKIA-{identity}'
            assert observed.secret_access_key == f'secret-{identity}'
            assert observed.session_token == f'token-{identity}'
            assert observed.source == 'jwt'

            # Requirement 6.1 / 6.3: the partition served is the value derived for
            # this identity, and never a value derived for a different identity.
            assert partition == partition_by_identity[identity]
            others = {partition_by_identity[other] for other in identities if other != identity}
            assert partition not in others

            # Requirement 6.3: the cache entry is keyed by this identity's own
            # identity_key and holds only this identity's derived value.
            assert cache_snapshot[(identity, region)] == partition_by_identity[identity]
