# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Phase 2 per-credential-context partition cache isolation tests.

Property-based tests for ``get_partition`` in ``utils/aws_utils.py`` while a
``RequestScopedCredentialResolver`` is active. This module is dedicated to
Property 17 (Partition cache isolation by identity); the sibling per-request
freshness property (Property 18) lives in a separate module to avoid file
conflicts.

The boto3/botocore mocking patterns mirror those established in
``tests/test_request_scoped_resolver.py`` and ``tests/test_credential_seam_routing.py``.
"""

import contextlib
from awslabs.aws_healthomics_mcp_server.utils.aws_utils import (
    CredentialContext,
    RequestScopedCredentialResolver,
    get_active_resolver,
    get_partition,
    reset_credential_context,
    set_active_resolver,
    set_credential_context,
)
from hypothesis import given, settings
from hypothesis import strategies as st
from unittest.mock import MagicMock, patch


# Distinct identity strings. Printable, non-space ASCII keeps the derived access
# key ids readable; ``unique=True`` guarantees each context carries a distinct
# identity (and therefore a distinct identity_key), which is what makes
# cross-identity cache leakage observable.
identity_lists = st.lists(
    st.text(
        alphabet=st.characters(min_codepoint=0x21, max_codepoint=0x7E),
        min_size=1,
        max_size=10,
    ),
    unique=True,
    min_size=2,
    max_size=5,
)

single_identity = st.text(
    alphabet=st.characters(min_codepoint=0x21, max_codepoint=0x7E),
    min_size=1,
    max_size=10,
)

# Region values used both in the partition cache key and passed to
# ``build_session``. A small set of realistic regions across partitions exercises
# the (identity_key, region) keying without affecting the partition the mocked
# STS call reports.
region_strategy = st.sampled_from(
    [
        'us-east-1',
        'us-west-2',
        'eu-west-1',
        'cn-north-1',
        'us-gov-west-1',
    ]
)


def _context_for(identity: str) -> CredentialContext:
    """Build a CredentialContext with a distinct identity_key and credentials."""
    return CredentialContext(
        identity_key=identity,
        access_key_id=f'AKIA-{identity}',
        secret_access_key=f'secret-{identity}',
        session_token=f'token-{identity}',
        source='explicit',
    )


def _make_build_session(partition_by_identity, sts_calls):
    """Return a ``CredentialContext.build_session`` replacement keyed by identity.

    The session built for a given context returns an STS client whose
    ``get_caller_identity`` yields an ARN carrying that identity's partition. The
    ``identity_key`` selects which partition/ARN to return, and every
    ``get_caller_identity`` invocation is counted per identity in ``sts_calls`` so
    memoization (no second STS call for a cached identity+region) is observable.
    """

    def build_session(self, region):
        identity = self.identity_key
        partition = partition_by_identity[identity]
        arn = f'arn:{partition}:sts::000000000000:assumed-role/role/{identity}'

        def _record():
            sts_calls[identity] = sts_calls.get(identity, 0) + 1
            return {'Arn': arn}

        sts_client = MagicMock()
        sts_client.get_caller_identity.side_effect = _record
        session = MagicMock()
        session.client.return_value = sts_client
        return session

    return build_session


@contextlib.contextmanager
def _active_request_scoped_resolver():
    """Install a ``RequestScopedCredentialResolver`` and restore the original on exit.

    Implemented as a context manager (rather than a function-scoped fixture) so it
    resets cleanly for every input generated by ``@given``. The partition cache is
    cleared on entry and exit so cross-example state never leaks.
    """
    original = get_active_resolver()
    set_active_resolver(RequestScopedCredentialResolver())
    get_partition.cache_clear()  # type: ignore[attr-defined]
    try:
        yield
    finally:
        get_partition.cache_clear()  # type: ignore[attr-defined]
        set_active_resolver(original)


class TestPartitionCacheIsolation:
    """Property: Partition cache isolation by identity.

    Validates: Requirements Per-credential-context caching.
    """

    @given(identities=identity_lists, region=region_strategy)
    @settings(max_examples=100)
    def test_partition_is_isolated_by_identity(self, identities, region):
        """Property: Partition cache isolation by identity.

        For any set of credential contexts that resolve to different caller
        identities, the partition served to a request under one context is the
        value derived for that context's own identity and is never a value cached
        for a different context. Each identity is mapped to a distinct partition,
        so any cross-identity leakage would surface as an identity receiving a
        partition that belongs to another identity.

        Validates: Requirements Per-credential-context caching.
        """
        partition_by_identity = {
            identity: f'awspart{index}' for index, identity in enumerate(identities)
        }
        sts_calls: dict[str, int] = {}
        contexts = {identity: _context_for(identity) for identity in identities}

        with (
            _active_request_scoped_resolver(),
            patch.object(
                CredentialContext,
                'build_session',
                _make_build_session(partition_by_identity, sts_calls),
            ),
        ):
            results: dict[str, str] = {}
            for identity in identities:
                token = set_credential_context(contexts[identity])
                try:
                    results[identity] = get_partition(region_name=region)
                finally:
                    reset_credential_context(token)

        for identity in identities:
            # Each request received the partition derived for its own identity.
            assert results[identity] == partition_by_identity[identity]
            # And never a value cached for a different identity.
            others = {partition_by_identity[other] for other in identities if other != identity}
            assert results[identity] not in others

    @given(identity=single_identity, region=region_strategy)
    @settings(max_examples=100)
    def test_repeated_resolution_returns_same_cached_partition(self, identity, region):
        """Property: Partition cache isolation by identity (memoization arm).

        For any single identity and region, repeated resolution returns the same
        cached partition and does not re-derive it: the second call is served from
        the per-context cache, so STS ``get_caller_identity`` is invoked exactly
        once for that identity+region.

        Validates: Requirements Per-credential-context caching.
        """
        partition_by_identity = {identity: 'aws-test-partition'}
        sts_calls: dict[str, int] = {}
        context = _context_for(identity)

        with (
            _active_request_scoped_resolver(),
            patch.object(
                CredentialContext,
                'build_session',
                _make_build_session(partition_by_identity, sts_calls),
            ),
        ):
            token = set_credential_context(context)
            try:
                first = get_partition(region_name=region)
                second = get_partition(region_name=region)
            finally:
                reset_credential_context(token)

        assert first == second == 'aws-test-partition'
        # The cached value is reused on the second call; STS is consulted once.
        assert sts_calls[identity] == 1


class TestPartitionCacheBounded:
    """The per-context partition cache is bounded to avoid unbounded growth."""

    def test_cache_size_stays_within_bound(self):
        """Serving more distinct identities than the bound never grows past it.

        A long-running multi-tenant endpoint may serve an unbounded number of
        distinct caller identities. The per-context cache must not grow without
        limit: once the configured maximum is exceeded, the oldest entries are
        evicted so the cache size stays at or below the bound. Eviction only forces
        a re-derivation on a later cold miss; correctness is unaffected because the
        cache key always embeds ``identity_key``.
        """
        from awslabs.aws_healthomics_mcp_server.utils import aws_utils

        bound = aws_utils._MAX_PARTITION_CACHE_ENTRIES
        overflow = bound + 25
        partition_by_identity = {str(i): 'aws' for i in range(overflow)}
        sts_calls: dict[str, int] = {}

        with (
            _active_request_scoped_resolver(),
            patch.object(
                CredentialContext,
                'build_session',
                _make_build_session(partition_by_identity, sts_calls),
            ),
        ):
            for i in range(overflow):
                token = set_credential_context(_context_for(str(i)))
                try:
                    assert get_partition(region_name='us-east-1') == 'aws'
                finally:
                    reset_credential_context(token)
                # The cache is never allowed to exceed the configured bound.
                assert len(aws_utils._partition_cache) <= bound

            # After serving more identities than the bound, the cache is saturated
            # at exactly the bound (oldest entries evicted).
            assert len(aws_utils._partition_cache) == bound
