# This workflow runs an automated pull request code review when labeled
name: Check License Header
on:
  push:
  workflow_dispatch:
permissions: {}
jobs:
  precheck:
    name: Code Review Upon All Successful Runs
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Check license headers
        uses: viperproject/check-license-header@e06c65614fa9f32e099838df4dd25440c5344b32 # v2.0.3
        with:
          path: .
          config: ./.github/workflows/check-license-header.json
          strict: true
